export const optionsCategory = [
  { name: 'Beef', slug: 'beef' },
  { name: 'Breakfast', slug: 'breakfast' },
  { name: 'Chicken', slug: 'chicken' },
  { name: 'Dessert', slug: 'dessert' },
  { name: 'Goat', slug: 'goat' },
  { name: 'Lamb', slug: 'lamb' },
  { name: 'Miscellaneous', slug: 'miscellaneous' },
  { name: 'Pasta', slug: 'pasta' },
  { name: 'Pork', slug: 'pork' },
  { name: 'Seafood', slug: 'seafood' },
  { name: 'Side', slug: 'side' },
  { name: 'Starter', slug: 'starter' },
  { name: 'Vegan', slug: 'Vegan' },
  { name: 'Vegetarian', slug: 'Vegetarian' }
];

export const optionsArea = [
  { name: 'American', slug: 'american' },
  { name: 'British', slug: 'british' },
  { name: 'Canadian', slug: 'canadian' },
  { name: 'Chinese', slug: 'Chinese' },
  { name: 'Dutch', slug: 'Dutch' },
  { name: 'Egyptian', slug: 'Egyptian' },
  { name: 'French', slug: 'French' },
  { name: 'Greek', slug: 'Greek' },
  { name: 'Indian', slug: 'Indian' },
  { name: 'Irish', slug: 'Irish' },
  { name: 'Italian', slug: 'Italian' },
  { name: 'Jamaican', slug: 'Jamaican' },
  { name: 'Japanese', slug: 'Japanese' },
  { name: 'Kenyan', slug: 'Kenyan' },
  { name: 'Malaysian', slug: 'Malaysian' },
  { name: 'Mexican', slug: 'Mexican' },
  { name: 'Moroccan', slug: 'Moroccan' },
  { name: 'Polish', slug: 'Polish' },
  { name: 'Portuguese', slug: 'Portuguese' },
  { name: 'Russian', slug: 'Russian' },
  { name: 'Spanish', slug: 'Spanish' },
  { name: 'Thai', slug: 'Thai' },
  { name: 'Tunisian', slug: 'Tunisian' },
  { name: 'Turkish', slug: 'Turkish' },
  { name: 'Unknown', slug: 'Unknown' },
  { name: 'Vietnamese', slug: 'Vietnamese' }
];
